name: Deploy .NET API to MonsterASP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # or 7.0.x if you use .NET 7

      - name: Clean previous publish folder
        run: |
          if (Test-Path "${{ github.workspace }}\publish") { Remove-Item -Recurse -Force "${{ github.workspace }}\publish" }

      - name: Build and Publish
        run: dotnet publish ${{ github.workspace }}/TrackerAPI.csproj -c Release -o ${{ github.workspace }}/publish

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}        # 155.254.246.42 OR all-in-one-tracker-api.somee.com
          username: ${{ secrets.FTP_USERNAME }}    # sanchi
          password: ${{ secrets.FTP_PASSWORD }}    # your Somee FTP password
          protocol: ftp
          port: 21
          local-dir: ./publish/
          server-dir: /www.all-in-one-tracker-api.somee.com/
          log-level: verbose
